version: '3.5'
services:

##########################################################################
#  CORE SERVICES
##########################################################################
  nginx:
    container_name: nginx
    image: ${NGINX}
    restart: unless-stopped
    networks:
      - simplilearn
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/:/etc/nginx/
      - ./certs:/etc/nginx/certs

##########################################################################
#  CI/CD Application(s) and Service(s)
##########################################################################

  # Jenkins Nodes
  jenkins-master:
    container_name: jenkins-master
    build:
      context: .
      dockerfile: ./docker-files/Jenkins.Dockerfile
    user: root
    restart: unless-stopped
    networks:
      - simplilearn
    environment:
      SNAPSHOT_URL: "http://nexus:8081/repository/maven-snapshots/"
      RELEASE_URL: "http://nexus:8081/repository/maven-releases/"
      GROUP_URL: "http://nexus:8081/repository/maven-group/"
    volumes:
      - jenkins_master_data:/var/jenkins_home:z
      - /etc/docker:/etc/docker
      - "/root/.docker:$HOME/.docker"
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf/.ssh:/var/jenkins_home/.ssh
      - ./conf/.m2:/var/jenkins_home/.m2

  jenkins-node01:
    container_name: jenkins-node01
    build:
      context: .
      dockerfile: ./docker-files/Jenkins.Dockerfile
    user: root
    restart: unless-stopped
    networks:
      - simplilearn
    environment:
      SNAPSHOT_URL: "http://nexus:8081/repository/maven-snapshots/"
      RELEASE_URL: "http://nexus:8081/repository/maven-releases/"
      GROUP_URL: "http://nexus:8081/repository/maven-group/"
    volumes:
      - jenkins_node01_data:/var/jenkins_home:z
      - /etc/docker:/etc/docker
      - "/root/.docker:$HOME/.docker"
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf/.ssh:/var/jenkins_home/.ssh
      - ./conf/.m2:/var/jenkins_home/.m2

  jenkins-node02:
    container_name: jenkins-node02
    build:
      context: .
      dockerfile: ./docker-files/Jenkins.Dockerfile
    user: root
    restart: unless-stopped
    networks:
      - simplilearn
    environment:
      SNAPSHOT_URL: "http://nexus:8081/repository/maven-snapshots/"
      RELEASE_URL: "http://nexus:8081/repository/maven-releases/"
      GROUP_URL: "http://nexus:8081/repository/maven-group/"
    volumes:
      - jenkins_node02_data:/var/jenkins_home:z
      - /etc/docker:/etc/docker
      - "/root/.docker:$HOME/.docker"
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf/.ssh:/var/jenkins_home/.ssh
      - ./conf/.m2:/var/jenkins_home/.m2

  # Repository Manager
  nexus:
    container_name: nexus
    image: ${NEXUS}
    restart: unless-stopped
    networks:
      - simplilearn
    volumes:
      - nexus_data:/nexus-data:z

##########################################################################
#  CM Application(s) and Service(s)
##########################################################################
  ansible:
    container_name: ansible
    build:
      context: .
      dockerfile: ./docker-files/Ansible.Dockerfile
    user: root
    restart: unless-stopped
    networks:
      - simplilearn
    volumes:
      - ./conf/ansible/playbooks:/playbooks

##########################################################################
#  Application - Tomcat Server
##########################################################################
  tomcat:
    container_name: tomcat
    build:
      context: .
      dockerfile: ./docker-files/Tomcat.Dockerfile
    user: root
    restart: unless-stopped
    networks:
      - simplilearn

volumes:
  jenkins_master_data:
  jenkins_node01_data:
  jenkins_node02_data:
  nexus_data:

networks:
  simplilearn:
    driver: bridge
